kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name | quote }}
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
  - name: web
    port: 8085
    targetPort: 8085
  selector:
    name: {{ .Values.name | quote }}
